const express=require('express');const cors=require('cors');const path=require('path');const WebSocket=require('ws');
const app=express();app.use(cors());app.use(express.json({limit:'2mb'}));
const PORT=process.env.PORT||3000, DISPLAY_SYMBOL=process.env.DISPLAY_SYMBOL||'F-XACM-NSI-202607', FEED_SYMBOL=process.env.FEED_SYMBOL||'F-XACM-NSI-202607', PRODUCT_NAME=process.env.PRODUCT_NAME||'Nano Silver 07/2026', PRICE_WS=process.env.SFVN_PRICE_WS||'wss://client-uat.mapsinfotech.com/v2/ws/maps/price', BRIDGE_KEY=process.env.VYRO_BRIDGE_KEY||'vyro-local-bridge-key';
let startedAt=Date.now(),sfvnStatus='BOOTING',lastSfvnError='',sfvnMsgCounter=0,sfvnMsgPerSec=0,acceptedPriceTicks=0,rejectedPriceTicks=0,bridgePackets=0,lastBridgeAt=0;
let sfvnPrice={displaySymbol:DISPLAY_SYMBOL,feedSymbol:'',productName:PRODUCT_NAME,priceSource:'SFVN_BID_SELL',price:null,bid:null,ask:null,spread:null,updatedAt:null};
let mt5AI={source:'MARKET_FLOW_ENGINE',status:'WAITING_BRIDGE',symbol:'NSI',mappedSymbol:'',tf:'M1',price:null,smn:0,power:0,delta:0,rsi:50,atr:0,emaFast:null,emaSlow:null,emaTrend:'NEUTRAL',emaCross:'NONE',bos:'NONE',choch:'NONE',liquidity:'NONE',stopHunt:'NONE',fakeBreakout:false,smartBias:'NEUTRAL',phase:'RANGING',grade:'WAIT',signal:'WAIT',score:0,reason:'Waiting CMD Python bridge',tp:null,sl:null,updatedAt:null,bridgeLatencyMs:null,candles:0,ticks:0};
function num(v,f=NaN){const n=Number(v);return Number.isFinite(n)?n:f}function dec(s){try{return JSON.parse(Buffer.from(s,'base64').toString('utf8'))}catch{return null}}function parse(raw){let m;try{m=JSON.parse(raw.toString())}catch{return[]}const p=m.payload;if(typeof p==='string'){const d=dec(p);return d?[d]:[]}if(Array.isArray(p))return p.map(x=>typeof x==='string'?dec(x):x).filter(Boolean);return p&&typeof p==='object'?[p]:[]}
function applyTick(t){if(String(t.s||'')!==FEED_SYMBOL)return;const bid=num(t.b??t.bid),ask=num(t.a??t.ask),last=num(t.lt??t.c??t.price??t.last);let price=NaN;if(Number.isFinite(bid)&&bid>20&&bid<200)price=bid;else if(Number.isFinite(ask)&&ask>20&&ask<200)price=ask;else if(Number.isFinite(last)&&last>20&&last<200)price=last;if(!Number.isFinite(price)){rejectedPriceTicks++;lastSfvnError='reject bad price';return}const safeBid=Number.isFinite(bid)&&bid>0?bid:price,safeAsk=Number.isFinite(ask)&&ask>0?ask:price;acceptedPriceTicks++;sfvnPrice={displaySymbol:DISPLAY_SYMBOL,feedSymbol:t.s||'',productName:PRODUCT_NAME,priceSource:'SFVN_BID_SELL',price,bid:safeBid,ask:safeAsk,spread:Math.abs(safeAsk-safeBid),updatedAt:new Date().toISOString()}}
function connectSfvn(){sfvnStatus='CONNECTING';const ws=new WebSocket(PRICE_WS);ws.on('open',()=>{sfvnStatus='LIVE';lastSfvnError='';ws.send(JSON.stringify({key:{domainName:'',prefix:'',messageName:'subscribe',suffix:'v1',messageType:'tick_price'},payload:`ticker@${FEED_SYMBOL}`}));console.log('[V46] SFVN connected',FEED_SYMBOL)});ws.on('message',raw=>{sfvnMsgCounter++;parse(raw).forEach(applyTick)});ws.on('error',e=>{sfvnStatus='ERROR';lastSfvnError=e.message});ws.on('close',(c,r)=>{sfvnStatus='RECONNECTING';lastSfvnError=`closed ${c} ${r||''}`;setTimeout(connectSfvn,3000)})}setInterval(()=>{sfvnMsgPerSec=sfvnMsgCounter;sfvnMsgCounter=0},1000);connectSfvn();
function safe(v,d=3){const n=Number(v);return Number.isFinite(n)?Number(n.toFixed(d)):null}function auth(req,res,next){const k=req.headers['x-vyro-key']||req.query.key;if(BRIDGE_KEY&&k!==BRIDGE_KEY)return res.status(401).json({ok:false,error:'unauthorized'});next()}
app.post('/api/bridge/mt5',auth,(req,res)=>{const p=req.body||{},now=Date.now();bridgePackets++;lastBridgeAt=now;mt5AI={source:'MARKET_FLOW_ENGINE',status:'LIVE',symbol:p.symbol||'NSI',mappedSymbol:p.mappedSymbol||p.mt5_symbol||'',tf:p.tf||'M1',price:safe(p.price,3),smn:safe(p.smn,2)||0,power:safe(p.power,2)||0,delta:safe(p.delta,2)||0,rsi:safe(p.rsi,1)||50,atr:safe(p.atr,3)||0,emaFast:safe(p.emaFast,3),emaSlow:safe(p.emaSlow,3),emaTrend:p.emaTrend||'NEUTRAL',emaCross:p.emaCross||'NONE',bos:p.bos||'NONE',choch:p.choch||'NONE',liquidity:p.liquidity||'NONE',stopHunt:p.stopHunt||'NONE',fakeBreakout:!!p.fakeBreakout,smartBias:p.smartBias||'NEUTRAL',phase:p.phase||'RANGING',grade:p.grade||'WAIT',signal:p.signal||'WAIT',score:Math.max(0,Math.min(100,Math.round(num(p.score,0)))),reason:p.reason||'AI update',tp:safe(p.tp,3),sl:safe(p.sl,3),updatedAt:new Date().toISOString(),bridgeLatencyMs:p.clientTime?now-Number(p.clientTime):null,candles:Number(p.candles||0),ticks:Number(p.ticks||0)};res.json({ok:true,bridgePackets})});
app.get('/api/live',(req,res)=>{const age=lastBridgeAt?Date.now()-lastBridgeAt:null,mt5Status=age!=null&&age<15000?'LIVE':'STALE';res.json({ok:true,mode:'HYBRID_SFVN_PRICE_MT5_AI',uptime:Math.floor((Date.now()-startedAt)/1000),sfvn:{status:sfvnStatus,msgPerSec:sfvnMsgPerSec,lastError:lastSfvnError,acceptedPriceTicks,rejectedPriceTicks,price:sfvnPrice},mt5:{status:mt5Status,bridgePackets,lastBridgeAt,ageMs:age,ai:mt5AI},display:{symbol:DISPLAY_SYMBOL,productName:PRODUCT_NAME,price:sfvnPrice.price,bid:sfvnPrice.bid,ask:sfvnPrice.ask,spread:sfvnPrice.spread,signal:mt5AI.signal,score:mt5AI.score,reason:mt5AI.reason,tp:mt5AI.tp,sl:mt5AI.sl,smn:mt5AI.smn,power:mt5AI.power,delta:mt5AI.delta,rsi:mt5AI.rsi,atr:mt5AI.atr,emaFast:mt5AI.emaFast,emaSlow:mt5AI.emaSlow,emaTrend:mt5AI.emaTrend,emaCross:mt5AI.emaCross,bos:mt5AI.bos,choch:mt5AI.choch,liquidity:mt5AI.liquidity,stopHunt:mt5AI.stopHunt,fakeBreakout:mt5AI.fakeBreakout,smartBias:mt5AI.smartBias,phase:mt5AI.phase,grade:mt5AI.grade,updatedAt:mt5AI.updatedAt}})});
app.get('/api/price/sfvn',(req,res)=>res.json({ok:true,status:sfvnStatus,sfvnPrice}));app.get('/api/bridge/status',(req,res)=>res.json({ok:true,bridgePackets,lastBridgeAt,mt5AI}));app.use(express.static(path.join(__dirname,'../frontend')));app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'../frontend/index.html')));app.listen(PORT,()=>console.log('[V46] Hybrid running',PORT));
